# replace held item with map
# specifically only map # and display Name
data modify storage explorer_atlas:temp atlas.tag.map set from storage explorer_atlas:temp found_map.tag.map
data modify storage explorer_atlas:temp atlas.tag.display.MapColor set value 7492890
# the display.Name is generated by the copy_found_map_name item modifier in update_mainhand or update_offhand
